### ISSUE TITLE
Is v0.0.6 ready to publish?

### ISSUE THREAD

**Issue by geekytime** [spencerkohan/neo4ji#5]
I'd love to use the latest version in master, if you think it's ready to go. My main interest is in using the version that uses `sync-exec` instead of `execSync`, which requires node-gyp.

I could use the github url to install, but I prefer to maintain semver consistency when I can. :smile_cat:

**Comment by spencerkohan** [comment]
Hey @geekytime I just published 0.0.6 to npm - is that what you were looking for?

**Comment by geekytime** [comment]
Yeah, cool. I'll give it a try on Monday. Thanks!
