### ISSUE TITLE
Wget uses wrong flag for output file (-o instead of -O)

### ISSUE THREAD

**Issue by elsbree** [spencerkohan/neo4ji#6]
The `wget` command on [this](https://github.com/spencerkohan/neo4ji/blob/master/neo4ji.js#L73) line uses `wget -o` where it should use `wget -O` to specify the download destination. See [here](http://stackoverflow.com/a/31667928/1536504).

This causes the `tar` command on [line 135](https://github.com/spencerkohan/neo4ji/blob/master/neo4ji.js#L135) to fail, making neo4ji quit with an error. I'm happy to submit a PR for this.

**Comment by spencerkohan** [comment]
Thanks for catching that @elsbree.  Yeah sure submit a PR and I will take a look and accept.

**Comment by elsbree** [comment]
Just submitted. Easiest PR ever :D

**Comment by spencerkohan** [comment]
Just merged thanks!
